
set TOOLCHAIN_PATH=C:\toolchain

set TOOLCHAIN_CMAKE=%TOOLCHAIN_PATH%\cmake\3.12.4\bin
set TOOLCHAIN_NINJA=%TOOLCHAIN_PATH%\ninja\1.9.0\bin

set TOOLCHAIN_CC_TDM_GCC_MINGW_GCC=C%TOOLCHAIN_PATH%\compiler\tdm_gcc_mingw\4.6.1

set PATH=%TOOLCHAIN_CMAKE%;%TOOLCHAIN_NINJA%;%TOOLCHAIN_CC_TDM_GCC_MINGW_GCC%\bin;%PATH%;
