# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-2019,  cc: "cl",    cxx: "cl",      gen: "Visual Studio 16 2019"  }
          - { name: "Windows gcc",  os: windows-2019,  cc: "gcc",   cxx: "g++",     gen: "Ninja"  }
          - { name: "Ubuntu gcc",   os: ubuntu-20.04,  cc: "gcc",   cxx: "g++",     gen: "Ninja"  }
          - { name: "Ubuntu clang", os: ubuntu-20.04,  cc: "clang", cxx: "clang++", gen: "Ninja"  }
          - { name: "MacOS clang",  os: macos-latest,  cc: "clang", cxx: "clang++", gen: "Ninja"  }
        build_type: [Release, Debug]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          # ninja version to download. Default: 1.10.0
          version: 1.10.0

      # Cmake
      - name: Configure CMake
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          mkdir build 
          cmake -B "${{github.workspace}}/build" \ 
            -S "${{github.workspace}}/source/." \
            -G "${{ matrix.config.gen }}" \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          ...

      # Build
      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build
